[build]
builder = "nixpacks"
buildCommand = "npm install && prisma generate && prisma migrate deploy && prisma db seed"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
